#!/bin/zsh
set -eux

project_dir=${0:a:h}

cd /etc/udev/rules.d/
sudo ln -sfv $(realpath --relative-to=. $project_dir/uinput.rules) .

cd ~/.config/systemd/user/

ln -sfv $(realpath --relative-to=. $project_dir/xkeysnail.service) .
